<#
.SYNOPSIS
  Locate a Steam installation of Timberborn (AppID 1062090) on Windows and print
  the paths the Timberbot build needs, as JSON. Read-only: nothing is written.

.DESCRIPTION
  Resolution order:
    1. Steam install path from the registry (HKCU\Software\Valve\Steam\SteamPath,
       then HKLM\SOFTWARE\WOW6432Node\Valve\Steam\InstallPath).
    2. Every library folder listed in <Steam>\steamapps\libraryfolders.vdf.
    3. The library that contains steamapps\appmanifest_1062090.acf wins.
  Also reports the user mod folder (Documents\Timberborn\Mods) and the Workshop
  content folder, and the game's file version from Timberborn.exe.

  Nothing here is a Timberbot runtime dependency; it is a Phase 1 helper so that
  Directory.Build.props (git-ignored) can be filled in without guessing.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\locate-timberborn.ps1
  powershell -ExecutionPolicy Bypass -File scripts\locate-timberborn.ps1 -AsProps
#>
[CmdletBinding()]
param(
    # Emit a Directory.Build.props snippet instead of JSON.
    [switch]$AsProps
)

$ErrorActionPreference = 'Stop'
$AppId = '1062090'

function Get-SteamRoot {
    $candidates = @()
    try { $v = (Get-ItemProperty -Path 'HKCU:\Software\Valve\Steam' -ErrorAction Stop).SteamPath; if ($v) { $candidates += $v } } catch {}
    try { $v = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Valve\Steam' -ErrorAction Stop).InstallPath; if ($v) { $candidates += $v } } catch {}
    $candidates += "${env:ProgramFiles(x86)}\Steam", "$env:ProgramFiles\Steam"
    foreach ($c in $candidates) {
        if ($c -and (Test-Path (Join-Path $c 'steamapps'))) { return (Resolve-Path $c).Path }
    }
    return $null
}

function Get-LibraryFolders([string]$steamRoot) {
    $libs = @($steamRoot)
    $vdf = Join-Path $steamRoot 'steamapps\libraryfolders.vdf'
    if (Test-Path $vdf) {
        # Lines look like:   "path"    "D:\\SteamLibrary"
        foreach ($m in [regex]::Matches((Get-Content $vdf -Raw), '"path"\s+"([^"]+)"')) {
            $p = $m.Groups[1].Value -replace '\\\\', '\'
            if (Test-Path $p) { $libs += $p }
        }
    }
    return $libs | Select-Object -Unique
}

function Get-AcfValue([string]$acfText, [string]$key) {
    $m = [regex]::Match($acfText, ('"{0}"\s+"([^"]*)"' -f [regex]::Escape($key)))
    if ($m.Success) { return $m.Groups[1].Value } else { return $null }
}

$steamRoot = Get-SteamRoot
$result = [ordered]@{
    steamRoot        = $steamRoot
    libraryFolders   = @()
    appManifest      = $null
    installDir       = $null
    managedDir       = $null
    gameExe          = $null
    gameFileVersion  = $null
    buildId          = $null
    userModDir       = (Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'Timberborn\Mods')
    timberbotModDir  = (Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'Timberborn\Mods\Timberbot')
    workshopDir      = $null
    dotnetSdks       = @()
    notes            = @()
}

if (-not $steamRoot) {
    $result.notes += 'Steam not found in registry or default locations. Pass paths manually into Directory.Build.props.'
} else {
    $libs = Get-LibraryFolders $steamRoot
    $result.libraryFolders = @($libs)
    foreach ($lib in $libs) {
        $acf = Join-Path $lib "steamapps\appmanifest_$AppId.acf"
        if (Test-Path $acf) {
            $text = Get-Content $acf -Raw
            $folder = Get-AcfValue $text 'installdir'
            $result.appManifest = $acf
            $result.buildId = Get-AcfValue $text 'buildid'
            $result.installDir = Join-Path $lib "steamapps\common\$folder"
            $result.workshopDir = Join-Path $lib "steamapps\workshop\content\$AppId"
            break
        }
    }
    if (-not $result.installDir) {
        $result.notes += "appmanifest_$AppId.acf not found in any Steam library; is Timberborn installed via Steam?"
    }
}

if ($result.installDir -and (Test-Path $result.installDir)) {
    $managed = Join-Path $result.installDir 'Timberborn_Data\Managed'
    if (Test-Path $managed) { $result.managedDir = $managed } else { $result.notes += "Managed dir missing: $managed" }
    $exe = Join-Path $result.installDir 'Timberborn.exe'
    if (Test-Path $exe) {
        $result.gameExe = $exe
        $result.gameFileVersion = (Get-Item $exe).VersionInfo.ProductVersion
    }
    if (-not (Test-Path $result.workshopDir)) { $result.workshopDir = $null }
}

if (-not (Test-Path $result.userModDir)) { $result.notes += "User mod folder does not exist yet: $($result.userModDir) (the game creates it on first mod install; the csproj Deploy target creates the Timberbot subfolder)." }

try { $result.dotnetSdks = @((& dotnet --list-sdks 2>$null) | ForEach-Object { $_.Trim() }) } catch { $result.notes += 'dotnet SDK not on PATH.' }

if ($AsProps) {
    @"
<!-- Generated by scripts/locate-timberborn.ps1 on $(Get-Date -Format s). Keep this file git-ignored. -->
<Project>
  <PropertyGroup>
    <GameManagedDir>$($result.managedDir)</GameManagedDir>
    <ModDir>$($result.timberbotModDir)</ModDir>
  </PropertyGroup>
</Project>
"@
} else {
    $result | ConvertTo-Json -Depth 4
}
